// import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState } from '../../app/store';
import { initialGameboardState } from '../../lib/common/constants';
import { SHIP_AREA, ICellState } from '../../lib/common/types';
import { initializeGameboardState, generateRandomOwnShips, getGameboardStateAfterHit } from './functions';

type TPlayer = {
  name: string;
  ownShips: SHIP_AREA[];
  gameboardState: ICellState[];
}

type THit = {
  cellId: number;
  player: 'human' | 'cpu'
}

export interface IBegin {
  name: string;
  ownShips: SHIP_AREA[],

}

export interface BattleshipState {
  stage: 'initial' | 'game' | 'end';
  status: 'idle' | 'loading';
  humanPlayer: TPlayer;
  cpuPlayer: TPlayer;
}

const initialState: BattleshipState = {
  stage: 'initial',
  status: 'idle',
  humanPlayer: {
    name: '',
    ownShips: [],
    gameboardState: [],
  },
  cpuPlayer: {
    name: 'CPU',
    ownShips: [],
    gameboardState: [],
  },
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
// export const incrementAsync = createAsyncThunk(
//   'counter/fetchCount',
//   async (amount: number) => {
//     const response = await fetchCount(amount);
//     // The value we return becomes the `fulfilled` action payload
//     return response.data;
//   },
// );

export const battleshipSlice = createSlice({
  name: 'battleship',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    begin: (state, action: PayloadAction<IBegin>) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      const cpuShips:SHIP_AREA[] = generateRandomOwnShips([4, 3, 3, 3, 2]);
      state.humanPlayer.ownShips = action.payload.ownShips;
      state.humanPlayer.name = action.payload.name;
      state.humanPlayer.gameboardState = initializeGameboardState(action.payload.ownShips);
      state.cpuPlayer.ownShips = cpuShips;
      state.cpuPlayer.gameboardState = initializeGameboardState(cpuShips);
      state.stage = 'game';
    },
    hit: (state, action: PayloadAction<THit>) => {
      // when human choose a target cell (cpu cell)
      if (action.payload.player === 'cpu') {
        state.cpuPlayer.gameboardState = getGameboardStateAfterHit(
          action.payload.cellId,
          state.cpuPlayer.gameboardState,
          state.cpuPlayer.ownShips,
        );
      } else {
      // when is the cpu hit action
        state.humanPlayer.gameboardState = initialGameboardState;
      }
    },
    // decrement: (state) => {
    //   state.value -= 1;
    // },
    // // Use the PayloadAction type to declare the contents of `action.payload`
    // incrementByAmount: (state, action: PayloadAction<number>) => {
    //   state.value += action.payload;
    // },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  // extraReducers: (builder) => {
  //   builder
  //     .addCase(incrementAsync.pending, (state) => {
  //       state.status = 'loading';
  //     })
  //     .addCase(incrementAsync.fulfilled, (state, action) => {
  //       state.status = 'idle';
  //       state.value += action.payload;
  //     });
  // },
});

export const { begin } = battleshipSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectHumanPlayer = (state: RootState) => state.battleship.humanPlayer;
export const selectCpuPlayer = (state: RootState) => state.battleship.cpuPlayer;
export const selectStage = (state: RootState) => state.battleship.stage;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd = (amount: number): AppThunk => (
//   dispatch,
//   getState,
// ) => {
//   const currentValue = selectCount(getState());
//   if (currentValue % 2 === 1) {
//     dispatch(incrementByAmount(amount));
//   }
// };

export default battleshipSlice.reducer;
